---
base:
    site: Enfugue
    locale: en_US
    description: The Enfugue Web App brings StableDiffusion art to your browser, for free.
    author: 
        name: Benjamin Paine
        email: benjamin@enfugue.ai
    license:
        name: GNU Affero General Public License (AGPL) v3.0
        href: https://www.gnu.org/licenses/agpl-3.0.html
    social: []
    logo: /static/img/enfugue-logo.png
    android:
        icon:
            href: /static/img/favicon/favicon-128x128.png
            size: 128x128
            type: image/png
    windows:
        icon:
            href: /static/img/favicon/favicon-128x128.png
            size: 128x128
            type: image/png
    links:
        preconnect:
            - href: https://fonts.googleapis.com
            - href: https://fonts.gstatic.com
              crossorigin: null
        stylesheet:
            - href: /static/css/01-reset.min.css
            - href: /static/css/02-variables.min.css
            - href: /static/css/03-fonts.min.css
              media: print
              onload: this.media='all'
            - href: /static/css/04-base.min.css
            - href: /static/css/05-common.min.css
            - href: /static/css/06-header.min.css
            - href: /static/css/07-main.min.css
            - href: /static/css/08-enfugue.min.css
            - href: /static/css/09-enfugue-nodes.min.css
            - href: /static/css/vendor/fa/fontawesome.min.css
              media: print
              onload: this.media='all'
            - href: /static/css/vendor/fa/regular.min.css
              media: print
              onload: this.media='all'
            - href: /static/css/vendor/fa/brands.min.css
              media: print
              onload: this.media='all'
            - href: /static/css/vendor/fa/solid.min.css
              media: print
              onload: this.media='all'
        'shortcut icon':
            - href: /static/img/favicon/favicon.ico
              type: image/x-icon
        icon:
            - type: image/png
              sizes: 16x16
              href: /static/img/favicon/favicon-16x16.png
            - type: image/png
              sizes: 32x32
              href: /static/img/favicon/favicon-32x32.png
        apple-touch-icon:
            - sizes: 256x256
              href: /static/img/favicon/favicon-256x256.png
        manifest:
            - href: /manifest.json
    scripts:
        - src: /static/js/vendor/gpu/gpu-browser.min.js
        - src: /static/js/enfugue.mjs
          type: module
          async: null
    meta:
        charset: utf-8
        robots: noindex, nofollow
        viewport:
            'width=device-width, initial-scale=1,
            shrink-to-fit=no'
        theme-color: '#ddb33d'
        msapplication-tileColor: '#ddb33d'
        msapplication-config: /browserconfig.xml
        'twitter:card': summary
        'twitter:image': /static/img/enfugue-icon.png
    opengraph:
        type: website
        image: /static/img/enfugue-share.png
        'image:width': 1200
        'image:height': 628
